#!/usr/bin/env bash
# Highlights the focused AeroSpace workspace pill.
# $NAME is like "space.3"; FOCUSED_WORKSPACE comes from the trigger.

# --- Theme (generated by scripts/theme.sh) ---
[ -f "$HOME/.config/newmac/theme.sh" ] && . "$HOME/.config/newmac/theme.sh"
# Fallbacks (Tokyo Night) so the bar works before theme.sh has ever run.
: "${C_ACCENT:=0xffbb9af7}"    # focused pill background
: "${C_BASE:=0xff1a1b26}"      # dark icon on the accent pill
: "${C_SURFACE:=0xff24283b}"   # unfocused pill background
: "${C_TEXT:=0xffc0caf5}"      # unfocused icon

sid="${NAME#space.}"
if [ "$sid" = "$FOCUSED_WORKSPACE" ]; then
  sketchybar --set "$NAME" background.color=$C_ACCENT icon.color=$C_BASE
else
  sketchybar --set "$NAME" background.color=$C_SURFACE icon.color=$C_TEXT
fi
