#!/usr/bin/env bash
# ============================================================
#  docs.sh — regenerate docs/CATALOG.md from the catalog.
#  Run after editing scripts/catalog.sh or scripts/presets.sh:
#     bash scripts/docs.sh
#  The index can never drift from reality — it IS the catalog.
# ============================================================
set -uo pipefail

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPTS_DIR/.." && pwd)"
OUT="$REPO_DIR/docs/CATALOG.md"

source "$SCRIPTS_DIR/lib.sh"
source "$SCRIPTS_DIR/catalog.sh"
source "$SCRIPTS_DIR/presets.sh"

mkdir -p "$REPO_DIR/docs"

_install_hint() {  # kind + payload -> human install string
  case "$1" in
    brew)   echo "\`brew install $2\`" ;;
    cask)   echo "\`brew install --cask $2\`" ;;
    curl)   echo "vendor script: \`$2\`" ;;
    npm)    echo "\`bun i -g $2\`" ;;
    uv)     echo "\`uv tool install $2\`" ;;
    mas)    echo "App Store (\`mas\`, id ${2%%:*})" ;;
    rustup) echo "rustup (sh.rustup.rs)" ;;
    *)      echo "$1: $2" ;;
  esac
}

{
  echo "# newmac catalog — everything the picker offers"
  echo
  echo "> Auto-generated by \`scripts/docs.sh\` from \`scripts/catalog.sh\` — do not edit by hand."
  echo "> ✓ = installed by default. Core tools install always."
  echo

  # --- Core ---
  echo "## Core (always installed)"
  echo
  names=""
  i=0
  while [[ $i -lt ${#CAT_ID[@]} ]]; do
    [[ "${CAT_CATEGORY[$i]}" == core ]] && names="$names${names:+, }${CAT_NAME[$i]}"
    i=$((i+1))
  done
  echo "$names"
  echo

  # --- Categories ---
  for category in $NEWMAC_CATEGORIES; do
    echo "## $(newmac_category_title "$category")"
    echo
    echo "| | Tool | Install | Description |"
    echo "|---|---|---|---|"
    i=0
    while [[ $i -lt ${#CAT_ID[@]} ]]; do
      if [[ "${CAT_CATEGORY[$i]}" == "$category" ]]; then
        mark=""; [[ "${CAT_DEFAULT[$i]}" == on ]] && mark="✓"
        echo "| $mark | **${CAT_NAME[$i]}** (\`${CAT_ID[$i]}\`) | $(_install_hint "${CAT_KIND[$i]}" "${CAT_PAYLOAD[$i]}") | ${CAT_DESC[$i]} |"
      fi
      i=$((i+1))
    done
    echo
  done

  # --- Presets ---
  echo "## Presets"
  echo
  for p in $NEWMAC_PRESETS; do
    echo "### $(newmac_preset_title "$p") (\`--preset $p\`)"
    echo
    echo "$(newmac_preset_desc "$p")"
    echo
    ids="$(newmac_preset_ids "$p")"
    if [[ -z "$ids" ]]; then
      echo "_Uses the catalog defaults (✓ items above)._"
    else
      names=""
      for id in $ids; do
        i=0
        while [[ $i -lt ${#CAT_ID[@]} ]]; do
          [[ "${CAT_ID[$i]}" == "$id" ]] && names="$names${names:+, }${CAT_NAME[$i]}"
          i=$((i+1))
        done
      done
      echo "$names"
    fi
    echo
  done

  echo "## Themes"
  echo
  for f in "$REPO_DIR/config/themes"/*.sh; do
    [[ -f "$f" ]] || continue
    tid="$(basename "$f" .sh)"
    ttitle="$(. "$f"; echo "${THEME_TITLE:-$tid}")"
    echo "- **$ttitle** (\`$tid\`)"
  done
  echo
  echo "Switch any time: \`bash scripts/theme.sh <id>\`"
} > "$OUT"

ok "Wrote ${OUT#"$REPO_DIR"/}"
