#!/usr/bin/env bash
# ============================================================
#  docs.sh — regenerate docs/CATALOG.md from the catalog.
#  Run after editing scripts/catalog.sh or scripts/presets.sh:
#     bash scripts/docs.sh
#  The index can never drift from reality — it IS the catalog.
# ============================================================
set -uo pipefail

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPTS_DIR/.." && pwd)"
OUT="$REPO_DIR/docs/CATALOG.md"

source "$SCRIPTS_DIR/lib.sh"
source "$SCRIPTS_DIR/catalog.sh"
source "$SCRIPTS_DIR/presets.sh"

mkdir -p "$REPO_DIR/docs"

_install_hint() {  # kind + payload -> human install string
  case "$1" in
    brew)   echo "\`brew install $2\`" ;;
    cask)   echo "\`brew install --cask $2\`" ;;
    curl)   echo "vendor script: \`$2\`" ;;
    npm)    echo "\`bun i -g $2\`" ;;
    uv)     echo "\`uv tool install $2\`" ;;
    mas)    echo "App Store (\`mas\`, id ${2%%:*})" ;;
    rustup) echo "rustup (sh.rustup.rs)" ;;
    *)      echo "$1: $2" ;;
  esac
}

{
  echo "# newmac catalog — everything the picker offers"
  echo
  echo "> Auto-generated by \`scripts/docs.sh\` from \`scripts/catalog.sh\` — do not edit by hand."
  echo "> ✓ = installed by default. Core tools install always."
  echo

  # --- Core ---
  echo "## Core (always installed)"
  echo
  names=""
  i=0
  while [[ $i -lt ${#CAT_ID[@]} ]]; do
    [[ "${CAT_CATEGORY[$i]}" == core ]] && names="$names${names:+, }${CAT_NAME[$i]}"
    i=$((i+1))
  done
  echo "$names"
  echo

  # --- Categories ---
  for category in $NEWMAC_CATEGORIES; do
    echo "## $(newmac_category_title "$category")"
    echo
    echo "| | Tool | Install | Description |"
    echo "|---|---|---|---|"
    i=0
    while [[ $i -lt ${#CAT_ID[@]} ]]; do
      if [[ "${CAT_CATEGORY[$i]}" == "$category" ]]; then
        mark=""; [[ "${CAT_DEFAULT[$i]}" == on ]] && mark="✓"
        echo "| $mark | **${CAT_NAME[$i]}** (\`${CAT_ID[$i]}\`) | $(_install_hint "${CAT_KIND[$i]}" "${CAT_PAYLOAD[$i]}") | ${CAT_DESC[$i]} |"
      fi
      i=$((i+1))
    done
    echo
  done

  # --- Presets ---
  echo "## Presets"
  echo
  for p in $NEWMAC_PRESETS; do
    echo "### $(newmac_preset_title "$p") (\`--preset $p\`)"
    echo
    echo "$(newmac_preset_desc "$p")"
    echo
    ids="$(newmac_preset_ids "$p")"
    if [[ -z "$ids" ]]; then
      echo "_Uses the catalog defaults (✓ items above)._"
    else
      names=""
      for id in $ids; do
        i=0
        while [[ $i -lt ${#CAT_ID[@]} ]]; do
          [[ "${CAT_ID[$i]}" == "$id" ]] && names="$names${names:+, }${CAT_NAME[$i]}"
          i=$((i+1))
        done
      done
      echo "$names"
    fi
    echo
  done

  echo "## Themes"
  echo
  for f in "$REPO_DIR/config/themes"/*.sh; do
    [[ -f "$f" ]] || continue
    tid="$(basename "$f" .sh)"
    ttitle="$(. "$f"; echo "${THEME_TITLE:-$tid}")"
    echo "- **$ttitle** (\`$tid\`)"
  done
  echo
  echo "Switch any time: \`bash scripts/theme.sh <id>\`"
} > "$OUT"

ok "Wrote ${OUT#"$REPO_DIR"/}"

# ============================================================
#  SVG assets — generated from the theme files so the README
#  visuals can never drift from the real palettes.
# ============================================================
ASSETS="$REPO_DIR/docs/assets"
mkdir -p "$ASSETS"

# --- banner.svg (Tokyo Night, the default look) ----------------
{
  printf '<svg xmlns="http://www.w3.org/2000/svg" width="720" height="150" viewBox="0 0 720 150">\n'
  printf '  <rect width="720" height="150" rx="14" fill="#1a1b26"/>\n'
  printf '  <text x="48" y="72" font-family="ui-monospace,SFMono-Regular,Menlo,monospace" font-size="44" font-weight="bold" fill="#c0caf5">newmac</text>\n'
  printf '  <text x="48" y="104" font-family="ui-monospace,SFMono-Regular,Menlo,monospace" font-size="16" fill="#a9b1d6">your Mac, your way — pick a stack, fine-tune, install</text>\n'
  x=48
  for c in bb9af7 7aa2f7 f7768e 9ece6a e0af68 8ba4b0; do
    printf '  <circle cx="%d" cy="126" r="6" fill="#%s"/>\n' "$x" "$c"
    x=$((x + 22))
  done
  printf '</svg>\n'
} > "$ASSETS/banner.svg"
ok "Wrote docs/assets/banner.svg"

# --- themes.svg (one row per theme, real palettes) -------------
THEME_COUNT=0
for f in "$REPO_DIR/config/themes"/*.sh; do
  [[ -f "$f" ]] && THEME_COUNT=$((THEME_COUNT + 1))
done
{
  printf '<svg xmlns="http://www.w3.org/2000/svg" width="720" height="%d" viewBox="0 0 720 %d">\n' \
    "$((THEME_COUNT * 48 + 12))" "$((THEME_COUNT * 48 + 12))"
  y=6
  for f in "$REPO_DIR/config/themes"/*.sh; do
    [[ -f "$f" ]] || continue
    (
      source "$f"
      tid="$(basename "$f" .sh)"
      rx=8; srx=4
      if [[ "${T_RADIUS:-6}" == 0 ]]; then rx=0; srx=0; fi
      printf '  <text x="8" y="%d" font-family="ui-monospace,SFMono-Regular,Menlo,monospace" font-size="15" fill="#8b8b8b">%s</text>\n' \
        "$((y + 27))" "$tid"
      printf '  <rect x="150" y="%d" width="292" height="40" rx="%d" fill="#%s"/>\n' "$y" "$rx" "$T_BASE"
      sx=162
      for c in "$T_SURFACE" "$T_ACCENT" "$T_ACCENT2" "$T_RED" "$T_GREEN" "$T_YELLOW" "$T_BLUE" "$T_TEXT"; do
        printf '  <rect x="%d" y="%d" width="26" height="24" rx="%d" fill="#%s"/>\n' "$sx" "$((y + 8))" "$srx" "$c"
        sx=$((sx + 34))
      done
      printf '  <text x="458" y="%d" font-family="ui-monospace,SFMono-Regular,Menlo,monospace" font-size="14" fill="#8b8b8b">%s</text>\n' \
        "$((y + 27))" "$THEME_TITLE"
    )
    y=$((y + 48))
  done
  printf '</svg>\n'
} > "$ASSETS/themes.svg"
ok "Wrote docs/assets/themes.svg"
