#!/usr/bin/env bash
# ============================================================
#  install.sh — install everything selected in newmac.conf.
#  Generates a Brewfile from the catalog, runs brew bundle,
#  then handles rustup / npm / uv / vendor-script installs.
#
#    bash scripts/install.sh              # install selection
#    bash scripts/install.sh --dry-run    # show what would happen
#
#  Idempotent: safe to re-run; update.sh calls this too.
# ============================================================
set -uo pipefail

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPTS_DIR/.." && pwd)"
CONF="$REPO_DIR/newmac.conf"

source "$SCRIPTS_DIR/lib.sh"
source "$SCRIPTS_DIR/catalog.sh"

DRY=0
[[ "${1:-}" == "--dry-run" ]] && DRY=1

if [[ $DRY -eq 0 && "$(uname -s)" != "Darwin" ]]; then
  err "install.sh only runs on macOS (use --dry-run elsewhere)."; exit 1
fi

if [[ ! -f "$CONF" ]]; then
  info "No newmac.conf — using catalog defaults."
  bash "$SCRIPTS_DIR/configure.sh" --defaults
fi
# shellcheck disable=SC1090
source "$CONF"

_wanted() {  # catalog index selected? (core is always wanted)
  [[ "${CAT_CATEGORY[$1]}" == core ]] && return 0
  newmac_selected "${CAT_ID[$1]}"
}

# --- Install manifest: track what newmac itself installs --------
# Anything missing before this run that exists after it gets recorded,
# so `newmac list` / `newmac nuke` only ever touch what we added.
MANIFEST="$HOME/.config/newmac/installed.list"
PRE_MISSING=""
if [[ $DRY -eq 0 ]]; then
  i=0
  while [[ $i -lt ${#CAT_ID[@]} ]]; do
    if _wanted "$i" && ! newmac_is_installed "${CAT_KIND[$i]}" "${CAT_PAYLOAD[$i]}" "${CAT_ID[$i]}"; then
      PRE_MISSING="$PRE_MISSING ${CAT_ID[$i]}"
    fi
    i=$((i+1))
  done
fi

# --- 1. Generate the Brewfile ----------------------------------
BREWFILE="${TMPDIR:-/tmp}/newmac.Brewfile.$$"
TAPS=""
# App Store items need the `mas` CLI even if it wasn't picked itself.
NEED_MAS=0
i=0
while [[ $i -lt ${#CAT_ID[@]} ]]; do
  _wanted "$i" && [[ "${CAT_KIND[$i]}" == mas ]] && NEED_MAS=1
  i=$((i+1))
done
{
  echo "# Generated by newmac install.sh from newmac.conf — do not edit."
  [[ $NEED_MAS -eq 1 ]] && ! newmac_selected mas && echo "brew \"mas\""
  # taps first (derived from payloads like user/tap/name)
  i=0
  while [[ $i -lt ${#CAT_ID[@]} ]]; do
    if _wanted "$i"; then
      case "${CAT_KIND[$i]}" in
        brew|cask)
          payload="${CAT_PAYLOAD[$i]}"
          case "$payload" in
            */*/*)
              tap="${payload%/*}"
              case " $TAPS " in *" $tap "*) ;; *) TAPS="$TAPS $tap"; echo "tap \"$tap\"" ;; esac ;;
          esac ;;
      esac
    fi
    i=$((i+1))
  done
  i=0
  while [[ $i -lt ${#CAT_ID[@]} ]]; do
    if _wanted "$i"; then
      case "${CAT_KIND[$i]}" in
        brew) echo "brew \"${CAT_PAYLOAD[$i]}\"" ;;
        cask) echo "cask \"${CAT_PAYLOAD[$i]}\"" ;;
        mas)  # payload is <appstore-id>:<display name>
              echo "mas \"${CAT_PAYLOAD[$i]#*:}\", id: ${CAT_PAYLOAD[$i]%%:*}" ;;
      esac
    fi
    i=$((i+1))
  done
  # Custom packages added via the Rust picker (newmac-ui → browse/add).
  # These live only in the conf, not the catalog, so `newmac nuke` won't
  # track them — remove with `brew uninstall` if you no longer want them.
  for e in ${NEWMAC_EXTRA_BREW:-}; do echo "brew \"$e\""; done
  for e in ${NEWMAC_EXTRA_CASK:-}; do echo "cask \"$e\""; done
} > "$BREWFILE"

if [[ $DRY -eq 1 ]]; then
  head1 "Brewfile that would be installed"
  cat "$BREWFILE"
  head1 "Post-brew installs"
  i=0
  while [[ $i -lt ${#CAT_ID[@]} ]]; do
    if _wanted "$i"; then
      case "${CAT_KIND[$i]}" in
        rustup) echo "  rustup:  stable toolchain via sh.rustup.rs" ;;
        curl)   echo "  curl:    ${CAT_NAME[$i]}  <-  ${CAT_PAYLOAD[$i]}" ;;
        npm)    echo "  npm/bun: ${CAT_PAYLOAD[$i]}" ;;
        uv)     echo "  uv tool: ${CAT_PAYLOAD[$i]}" ;;
      esac
    fi
    i=$((i+1))
  done
  echo
  echo "Toggles: ricing=$NEWMAC_TOGGLE_RICING macos-defaults=$NEWMAC_TOGGLE_MACOS_DEFAULTS power=$NEWMAC_TOGGLE_POWER schedule=$NEWMAC_TOGGLE_SCHEDULE"
  rm -f "$BREWFILE"
  exit 0
fi

info "Installing Homebrew packages (this can take a while)…"
if brew bundle --file="$BREWFILE"; then
  ok "Brew packages complete."
else
  warn "Some Brewfile entries failed (see above). Continuing — fix with 'brew search <name>'."
fi
rm -f "$BREWFILE"

# --- 2. Rust ----------------------------------------------------
if newmac_selected rust; then
  if ! have rustc; then
    info "Installing Rust via rustup…"
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path
  fi
  [[ -f "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"
  have rustup && rustup default stable >/dev/null 2>&1 || true
  have rustc && ok "Rust ready: $(rustc --version)"
fi

# --- 3. Node LTS via fnm ---------------------------------------
if newmac_selected fnm && have fnm; then
  info "Installing Node LTS via fnm…"
  eval "$(fnm env)" 2>/dev/null || true
  fnm install --lts >/dev/null 2>&1 && fnm default lts-latest >/dev/null 2>&1 || true
  ok "Node: $(fnm exec --using=lts-latest node --version 2>/dev/null || echo 'installed')"
fi

# --- 4. npm-distributed CLIs (via bun, falling back to npm) ----
npm_global_install() {  # npm_global_install <package>
  if have bun; then
    bun install -g "$1" && return 0
  fi
  if have npm; then
    npm install -g "$1" && return 0
  elif have fnm; then
    fnm exec --using=lts-latest npm install -g "$1" && return 0
  fi
  return 1
}
i=0
while [[ $i -lt ${#CAT_ID[@]} ]]; do
  if _wanted "$i" && [[ "${CAT_KIND[$i]}" == npm ]]; then
    info "Installing ${CAT_NAME[$i]} (${CAT_PAYLOAD[$i]})…"
    npm_global_install "${CAT_PAYLOAD[$i]}" || warn "${CAT_NAME[$i]} install failed."
  fi
  i=$((i+1))
done

# --- 5. uv-distributed CLIs ------------------------------------
i=0
while [[ $i -lt ${#CAT_ID[@]} ]]; do
  if _wanted "$i" && [[ "${CAT_KIND[$i]}" == uv ]]; then
    if have uv; then
      info "Installing ${CAT_NAME[$i]} via uv…"
      uv tool install --upgrade "${CAT_PAYLOAD[$i]}" || warn "${CAT_NAME[$i]} install failed."
    else
      warn "uv not installed — skipping ${CAT_NAME[$i]}."
    fi
  fi
  i=$((i+1))
done

# --- 6. Vendor install scripts (Claude, Droid, Amp, Kimi, …) ---
# Each id doubles as the command name we probe for, except cursor.
curl_cmd_for() {
  case "$1" in
    cursor) echo "cursor-agent" ;;
    *)      echo "$1" ;;
  esac
}
i=0
while [[ $i -lt ${#CAT_ID[@]} ]]; do
  if _wanted "$i" && [[ "${CAT_KIND[$i]}" == curl ]]; then
    cmd="$(curl_cmd_for "${CAT_ID[$i]}")"
    if have "$cmd"; then
      ok "${CAT_NAME[$i]} already installed."
    else
      info "Installing ${CAT_NAME[$i]}…"
      curl -fsSL "${CAT_PAYLOAD[$i]}" | bash || warn "${CAT_NAME[$i]} install failed."
    fi
  fi
  i=$((i+1))
done

# --- Record what this run actually installed -------------------
if [[ -n "$PRE_MISSING" ]]; then
  mkdir -p "$(dirname "$MANIFEST")"
  touch "$MANIFEST"
  i=0
  while [[ $i -lt ${#CAT_ID[@]} ]]; do
    id="${CAT_ID[$i]}"
    case " $PRE_MISSING " in
      *" $id "*)
        if newmac_is_installed "${CAT_KIND[$i]}" "${CAT_PAYLOAD[$i]}" "$id" \
           && ! grep -qx "$id" "$MANIFEST" 2>/dev/null; then
          echo "$id" >> "$MANIFEST"
        fi ;;
    esac
    i=$((i+1))
  done
  ok "Manifest updated: $(grep -c . "$MANIFEST" 2>/dev/null || echo 0) items tracked (newmac list)."
fi

ok "Install pass complete."
