#!/usr/bin/env bash
# ============================================================
#  theme.sh — apply a colour theme across the whole rice:
#  sketchybar, JankyBorders, Ghostty, Rio and Starship.
#
#    bash scripts/theme.sh              # NEWMAC_THEME from newmac.conf, else tokyonight
#    bash scripts/theme.sh rosepine     # apply a specific theme
#
#  Themes live in config/themes/<id>.sh. Applying a theme:
#    1. writes ~/.config/newmac/theme.sh   (sourced by sketchybarrc/bordersrc)
#    2. writes ~/.config/ghostty/theme.conf (optional include in ghostty config)
#    3. rewrites the `palette = "…"` selector in config/starship.toml
#    4. reloads sketchybar / restarts borders if they are around
#
#  NOTE: must stay bash-3.2 compatible (stock macOS bash).
# ============================================================
set -uo pipefail

SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPTS_DIR/.." && pwd)"
THEMES_DIR="$REPO_DIR/config/themes"
CONF="$REPO_DIR/newmac.conf"

source "$SCRIPTS_DIR/lib.sh"

# --- List mode: swatches for every theme -----------------------
if [[ "${1:-}" == "--list" || "${1:-}" == "list" ]]; then
  CURRENT=""
  [[ -f "$CONF" ]] && source "$CONF" && CURRENT="${NEWMAC_THEME:-}"
  _swatch() {  # _swatch <hex> — truecolor block
    printf '\033[48;2;%d;%d;%dm  \033[0m' \
      "$((16#${1:0:2}))" "$((16#${1:2:2}))" "$((16#${1:4:2}))"
  }
  printf '\n'
  for f in "$THEMES_DIR"/*.sh; do
    [[ -f "$f" ]] || continue
    (
      source "$f"
      id="$(basename "$f" .sh)"
      mark=" "; [[ "$id" == "$CURRENT" ]] && mark="${c_green}●${c_reset}"
      shape="rounded"; [[ "${T_RADIUS:-6}" == 0 ]] && shape="sharp"
      printf ' %s %s%-12s%s ' "$mark" "$c_bold" "$id" "$c_reset"
      for c in "$T_BASE" "$T_SURFACE" "$T_ACCENT" "$T_ACCENT2" "$T_RED" "$T_GREEN" "$T_YELLOW" "$T_BLUE"; do
        _swatch "$c"
      done
      printf '  %s%s · %s%s\n' "$c_dim" "$THEME_TITLE" "$shape" "$c_reset"
    )
  done
  printf '\n%sApply one:  newmac theme <id>   (or: bash scripts/theme.sh <id>)%s\n' "$c_dim" "$c_reset"
  exit 0
fi

# --- Which theme? ----------------------------------------------
THEME_ID="${1:-}"
if [[ -z "$THEME_ID" ]]; then
  [[ -f "$CONF" ]] && source "$CONF"
  THEME_ID="${NEWMAC_THEME:-tokyonight}"
fi

THEME_FILE="$THEMES_DIR/$THEME_ID.sh"
if [[ ! -f "$THEME_FILE" ]]; then
  err "Unknown theme '$THEME_ID' (no $THEME_FILE)"
  info "Available themes:"
  for f in "$THEMES_DIR"/*.sh; do
    [[ -f "$f" ]] || continue
    b="$(basename "$f")"
    printf '  %s\n' "${b%.sh}"
  done
  exit 1
fi

source "$THEME_FILE"
head1 "Theme: $THEME_TITLE ($THEME_ID)"

# --- 1. ~/.config/newmac/theme.sh ------------------------------
# T_* are raw hex; C_* are sketchybar-format 0xAARRGGBB derivatives.
NEWMAC_STATE_DIR="$HOME/.config/newmac"
mkdir -p "$NEWMAC_STATE_DIR"
cat > "$NEWMAC_STATE_DIR/theme.sh" <<EOF
# Generated by scripts/theme.sh — do not edit by hand.
# Re-apply / switch with:  bash scripts/theme.sh <id>
THEME_ID="$THEME_ID"
THEME_TITLE="$THEME_TITLE"
THEME_GHOSTTY="$THEME_GHOSTTY"

# Raw palette (6-digit hex, no #)
T_BASE=$T_BASE
T_SURFACE=$T_SURFACE
T_TEXT=$T_TEXT
T_SUBTEXT=$T_SUBTEXT
T_ACCENT=$T_ACCENT
T_ACCENT2=$T_ACCENT2
T_RED=$T_RED
T_GREEN=$T_GREEN
T_YELLOW=$T_YELLOW
T_BLUE=$T_BLUE

# sketchybar / borders format (0xAARRGGBB)
C_BASE=0xff$T_BASE
C_SURFACE=0xff$T_SURFACE
C_TEXT=0xff$T_TEXT
C_SUBTEXT=0xff$T_SUBTEXT
C_ACCENT=0xff$T_ACCENT
C_ACCENT2=0xff$T_ACCENT2
C_RED=0xff$T_RED
C_GREEN=0xff$T_GREEN
C_YELLOW=0xff$T_YELLOW
C_BLUE=0xff$T_BLUE
C_BAR=0xf0$T_BASE

# Shape (themes may set T_RADIUS / T_BORDER_STYLE; sharp themes use 0 / square)
C_RADIUS=${T_RADIUS:-6}
C_BORDER_STYLE=${T_BORDER_STYLE:-round}
EOF
ok "Wrote $NEWMAC_STATE_DIR/theme.sh"

# --- 2. Ghostty ------------------------------------------------
# ghostty config has `config-file = ?theme.conf` (optional include).
mkdir -p "$HOME/.config/ghostty"
printf 'theme = %s\n' "$THEME_GHOSTTY" > "$HOME/.config/ghostty/theme.conf"
ok "Wrote ~/.config/ghostty/theme.conf (theme = $THEME_GHOSTTY)"

# --- 2b. Rio ---------------------------------------------------
# Rio's config.toml has `theme = "newmac"` -> ~/.config/rio/themes/newmac.toml.
# We synthesise a full 16-colour palette from the theme's 10 values.
mkdir -p "$HOME/.config/rio/themes"
cat > "$HOME/.config/rio/themes/newmac.toml" <<EOF
# Generated by scripts/theme.sh — $THEME_TITLE. Do not edit by hand.
[colors]
background      = "#$T_BASE"
foreground      = "#$T_TEXT"
cursor          = "#$T_ACCENT"
selection-background = "#$T_SURFACE"
selection-foreground = "#$T_TEXT"
black           = "#$T_SURFACE"
red             = "#$T_RED"
green           = "#$T_GREEN"
yellow          = "#$T_YELLOW"
blue            = "#$T_BLUE"
magenta         = "#$T_ACCENT"
cyan            = "#$T_ACCENT2"
white           = "#$T_TEXT"
light-black     = "#$T_SUBTEXT"
light-red       = "#$T_RED"
light-green     = "#$T_GREEN"
light-yellow    = "#$T_YELLOW"
light-blue      = "#$T_BLUE"
light-magenta   = "#$T_ACCENT"
light-cyan      = "#$T_ACCENT2"
light-white     = "#$T_TEXT"
EOF
ok "Wrote ~/.config/rio/themes/newmac.toml"

# --- 3. Starship palette selector ------------------------------
# Portable temp-file rewrite (sed -i differs between GNU and BSD).
STARSHIP_TOML="$REPO_DIR/config/starship.toml"
if [[ -f "$STARSHIP_TOML" ]]; then
  tmp="$STARSHIP_TOML.tmp.$$"
  awk -v id="$THEME_ID" '
    /^palette = / { print "palette = \"" id "\""; next }
    { print }
  ' "$STARSHIP_TOML" > "$tmp" && mv "$tmp" "$STARSHIP_TOML"
  ok "Set palette = \"$THEME_ID\" in config/starship.toml"
else
  warn "config/starship.toml not found — skipped starship"
fi

# --- 4. Nudge running services ---------------------------------
if have sketchybar && pgrep -x sketchybar >/dev/null 2>&1; then
  sketchybar --reload >/dev/null 2>&1 || true
  ok "Reloaded sketchybar"
else
  info "sketchybar not running — it will pick up the theme on next start"
fi
if have borders && have brew; then
  brew services restart borders >/dev/null 2>&1 || true
  ok "Restarted borders"
fi

info "Ghostty picks up the theme on reload (cmd+shift+,); Rio on restart."
ok "Done — $THEME_TITLE applied."
